//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NagibDemo
{
    [Serializable]
    public class ControlMsg : Message
    {
        public const string k_RosMessageName = "car_msgs/Control";
        public override string RosMessageName => k_RosMessageName;

        public sbyte speed;
        public short rotation;

        public ControlMsg()
        {
            this.speed = 0;
            this.rotation = 0;
        }

        public ControlMsg(sbyte speed, short rotation)
        {
            this.speed = speed;
            this.rotation = rotation;
        }

        public static ControlMsg Deserialize(MessageDeserializer deserializer) => new ControlMsg(deserializer);

        private ControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speed);
            deserializer.Read(out this.rotation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speed);
            serializer.Write(this.rotation);
        }

        public override string ToString()
        {
            return "ControlMsg: " +
            "\nspeed: " + speed.ToString() +
            "\nrotation: " + rotation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
