//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NagibDemo
{
    [Serializable]
    public class DisplayMsg : Message
    {
        public const string k_RosMessageName = "car_msgs/Display";
        public override string RosMessageName => k_RosMessageName;

        public string image;

        public DisplayMsg()
        {
            this.image = "";
        }

        public DisplayMsg(string image)
        {
            this.image = image;
        }

        public static DisplayMsg Deserialize(MessageDeserializer deserializer) => new DisplayMsg(deserializer);

        private DisplayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.image);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "DisplayMsg: " +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
