//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NagibDemo
{
    [Serializable]
    public class EncoderMsg : Message
    {
        public const string k_RosMessageName = "car_msgs/Encoder";
        public override string RosMessageName => k_RosMessageName;

        public long left;
        public long right;

        public EncoderMsg()
        {
            this.left = 0;
            this.right = 0;
        }

        public EncoderMsg(long left, long right)
        {
            this.left = left;
            this.right = right;
        }

        public static EncoderMsg Deserialize(MessageDeserializer deserializer) => new EncoderMsg(deserializer);

        private EncoderMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.left);
            deserializer.Read(out this.right);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.left);
            serializer.Write(this.right);
        }

        public override string ToString()
        {
            return "EncoderMsg: " +
            "\nleft: " + left.ToString() +
            "\nright: " + right.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
